### ISSUE TITLE
Google Images Search Results - unexpected URL on thumbnail image

### ISSUE THREAD

**Issue by gingerbeardman** [yimingliu/Remove-Google-Redirection#2] opened 2019-06-22 21:18 UTC
# Problem
The link on the thumbnail image in google images search results is different than expected when this extension is enabled.

 # Desired behaviour
(this is what google normally does)
- click thumbnail to expand it into more info
- cmd+click thumbnail to open more info in new window

# Actual behaviour
- click thumbnail to expand it into more info (this works)
- cmd+click thumbnail to opens image in new window (this is unexpected)

## compare 

google - link on image
- https://www.google.com/imgres?imgurl=https%3A%2F%2Fretrocdn.net%2Fimages%2Fthumb%2F0%2F0a%2FDCM_JP_20000310_2000-08.pdf%2Fpage4-194px-DCM_JP_20000310_2000-08.pdf.jpg&imgrefurl=https%3A%2F%2Fsegaretro.org%2Findex.php%3Ftitle%3DFile%3ADCM_JP_20000310_2000-08.pdf%26page%3D4&docid=JD9fURp8xdmlyM&tbnid=RBtKPm19PRBfSM%3A&vet=10ahUKEwi2r_rTgf7iAhUSohQKHZOeCNoQMwhLKAkwCQ..i&w=194&h=240&itg=1&client=safari&bih=1116&biw=1263&q=dreameye%20pdf&ved=0ahUKEwi2r_rTgf7iAhUSohQKHZOeCNoQMwhLKAkwCQ&iact=mrc&uact=8
![google-image](https://user-images.githubusercontent.com/49612/59968972-fe622f00-953a-11e9-9156-db9b84646df9.png)

google - link on caption
- https://segaretro.org/index.php?title=File:DCM_JP_20000310_2000-08.pdf&page=4
![google-link](https://user-images.githubusercontent.com/49612/59968971-fc986b80-953a-11e9-964f-07b07e3fb796.png)

---

this extension - link on image
- https://retrocdn.net/images/thumb/0/0a/DCM_JP_20000310_2000-08.pdf/page4-194px-DCM_JP_20000310_2000-08.pdf.jpg
![rgr-image](https://user-images.githubusercontent.com/49612/59968970-facea800-953a-11e9-8683-01afd2a3090d.png)

this extension - link on caption
- https://segaretro.org/index.php?title=File:DCM_JP_20000310_2000-08.pdf&page=4
![rgr-link](https://user-images.githubusercontent.com/49612/59968969-f86c4e00-953a-11e9-881a-cbfc50f8649a.png)

**Comment by yimingliu** [comment] 2019-06-22 21:45
Ok I see.  My thoughts:

- In this case, my opinion is that this is an intended behavior of the Remove Google Redirect extension (as it was originally written).

     The idea of this extension is that it removes google redirects when you cmd-click on a search result (like, for example in the normal Google Search for web pages).   So similarly here, when you cmd-click on the image, it should take you directly to the image, without going through Google again.  The More Info page is effectively a Google redirect page (`https://www.google.com/imgres?imgurl=...`), and it is analogous to the Google redirect for web search ( `https://www.google.com/url?sa=...` ), so it is being removed.  I think this is correct behavior.

- On the other hand, I also see your point that this More Info page in Image Search is useful.  Unlike the normal Google redirect (`google.com/url?...`) which is purely for Google tracking purposes and has no value to the user, this More Info gives more context to the image.  With the extension on, you can't get to this page.  There should be a way to get to this page, if the user wants (basically, disable the redirect behavior for image search).  

    Maybe this should involve a user toggle-able preference setting?  A check box somewhere to disable image-search redirects?  Would that be acceptable?

- It is also unfortunate that the click and cmd-click behaves differently -- one showing the Google redirect, one not.  They should at least be consistent; both should go to the same place, and cmd-click should open that place in a new window.  This is probably a bug.

**Comment by gingerbeardman** [comment] 2019-06-22 22:06
1. I thought so too
2. This would be a good enough solution for me
3. I agree, it took me a while to figure out what was going on because it was only happening "sometimes" (turned out to be when I was cmd+clicking to open in new window)

Thanks for your consideration

**Comment by yimingliu** [comment] 2019-07-06 00:13
Latest version 1.0.4 includes a preference to disable redirection with a checkbox in the containing app (the app that used to be completely useless beyond being launched to install the extension).  You should be able to just tick the checkbox and get the default Google image results page back.  May need to restart the browser after checking the checkbox (or at least refreshing Google if you have those open already).

Let me know if I introduced regressions.

**Comment by yimingliu** [comment] 2019-07-15 18:43
I'm closing this under the assumption it's fixed, and to get it off my github dash.  Feel free to comment or open a new issue if that isn't true.

**Closed as completed by yimingliu** 2019-07-15 18:43 UTC

**Comment by gingerbeardman** [comment] 2019-07-16 00:09
Yup, works for me — thanks!
